### ISSUE TITLE
Can't Edit Module

### ISSUE THREAD

**Issue by MDeBaise** [GusBeare/DNNContactForm#1]
Hello, 
Couple questions. 
1. Should I be able to get into the module to edit it? I would assume the fields are editable. I click "Edit Module" and get nothing but a solid white popup. 
2. I'm actually trying to use the Bootstrap form that came with my DNN Skin. The form design works with my site however it's not functional. I would like it to be functional and I was hoping I could drop that source code into this module so it would look the way I want it to and be functional. 

I appreciate ANY help with this. Many, many thanks!
Mike

**Comment by GusBeare** [comment]
Hi Mike. Hmm, I've not been working with DNN for some time now but I'll get the code up later this morning and check it out.
You won't be able to edit the module inside DNN but you should be able to edit the settings as per the instructions in the readme file.
Which version of DNN are you using?

**Comment by GusBeare** [comment]
If you are comfortable with Visual Studio and undwerstand DNN module dev then just clone my code and edit it to your needs. 
I can help you along.

**Comment by MDeBaise** [comment]
Cool. I'll look for the readme file and see if I can figure it out. I'm not a code writer however I can usually look at something and figure out where it needs to be changed or updated. I got the form in and setup and it works great, just need it to look like my form. :) Hopefully, what I want to do will work out. Since this isn't a code issue, should I close out of this here?

**Comment by MDeBaise** [comment]
It appears I need to edit the View.ascx file from: /httpdocs/DesktopModules/DNNContactFormModule/

**Comment by GusBeare** [comment]
Thanks Mike.  You can edit the view.ascx file in the module folder directly on the site and change the markup if required. i.e taylor the layout to your needs. I think that's what you are trying to do.

**Comment by GusBeare** [comment]
Yes, you got there!

**Comment by GusBeare** [comment]
Just bear in mind that if you do that and install the module again those changes will get overwritten.

**Comment by GusBeare** [comment]
ps: be careful not to change the control Id's as if you do it will break the code that works with them.

**Comment by MDeBaise** [comment]
Correct... I always copy and rename files so they stay in the event I need to reinstall...... well, here goes! Thank you for your help.

**Comment by GusBeare** [comment]
You're welcome, good luck!
